### ISSUE TITLE
Voice echo

### ISSUE THREAD

**Issue by sidchoudhary** [mslosarz/nextrtc-example-videochat#11]
Just after joining the room for voice chat, echo start and not able to hear any thing except echo, even while talking I can hear my own voice which troubles in understating the on going conversation.

**Comment by sidchoudhary** [comment]
You did great job, but this voice echo is annoying, I am a pure server side developer shifted from mobile domain, so don't know much about scripting side, I am consulting with some of my known, let see if I can  fix this using their help.

**Comment by mslosarz** [comment]
I'll disable voice from local stream :)

6 sty 2017 04:14 "sidchoudhary" <notifications@github.com> napisał(a):

**Comment by mslosarz** [comment]
I've committed fix for it (and deploy)

**Comment by obcardinal** [comment]
mslosarz, this can be fixed in the future?
