### ISSUE TITLE
How can I know there are the id rooms?

### ISSUE THREAD

**Issue by obcardinal** [mslosarz/nextrtc-example-videochat#14]
I need to check, if id created this room to join them.

**Comment by mslosarz** [comment]
There are two ways to create conversation. You can use join (when conversation wasn't exists then new one will be created), or use create (then you'll receive created signal with room id in signal content). If you want, you can write your own signal which will check if conversation with given name exists (details [here](https://nextrtc.org/archives/133))

**Comment by obcardinal** [comment]
Thank you for quick reply.

So, I have this: https://pastebin.com/Nm5QyRar
And when I try to run, I get exception:

> Invalid factory method 'addCustomJoinHandler': needs to have a non-void return type!

**Comment by mslosarz** [comment]
my mistake, return for example signal instead of void then spring context will be able to start.
I fixed documentation :)

**Comment by mslosarz** [comment]
You could autowire org.nextrtc.signalingserver.repository.Conversations. This repository has method Optional<Conversation> findBy(String conversationId). You can use them to check if conversation exists or not

**Comment by obcardinal** [comment]
Thank you.

But what to do, if I get NullPointerException?

```
resolver.addCustomHandler(Signal.fromString("join_exist"), (msg) ->
            InternalMessage.create()
                    .to(msg.getFrom())
                    .content(conversations.findBy(msg.getContent()) == null ? msg.getContent() : "NOT_CREATED")
                    .build()
                    .send()
        );
```

I want to check, if conversation is exist.
I check message and if this not equals NOT_CREATED, I join to this room.

Hmm...
I don't use Signal. Now, I use Signal.EMPTY and this works.

**Comment by obcardinal** [comment]
You are the best!
Thank you for this library!!!
