### ISSUE TITLE
not correct dependency

### ISSUE THREAD

**Issue by Zhambul** [mslosarz/nextrtc-example-videochat#18]
<dependency>
			<groupId>org.nextrtc.signalingserver</groupId>
			<artifactId>nextrtc-signaling-server</artifactId>
			<version>0.0.6-SNAPSHOT</version>
		</dependency>
should be changed to
<dependency>
			<groupId>org.nextrtc.signalingserver</groupId>
			<artifactId>nextrtc-signaling-server</artifactId>
			<version>0.0.6</version>
		</dependency>

**Comment by mslosarz** [comment]
now version is set to 1.0.0-RC1
