### ISSUE TITLE
How can I get two peers connected ?

### ISSUE THREAD

**Issue by jemacom** [mslosarz/nextrtc-example-videochat#2]
Is there a shared link like in "https://apprtc.appspot.com/" ?
INFO :
- the app is deployed on Wildfly AS 8.1
- wsURL : 'ws://localhost:8383/videochat/signaling' 
  
  Thanks in advance :+1:

**Comment by mslosarz** [comment]
there are two ways to create a shared link:
First one is handle "created" signal:

``` javascript
nextRTC.on('created', function(nextRTC, event) {
     event.content// here is a room number
});
```

Otherwise you can send:

``` javascript
nextRTC.create('id of my room') // this one in code which creates room
```

``` javascript
nextRTC.join('id of my room') // in other joining client code
```
