### ISSUE TITLE
join again to same room after leave the room

### ISSUE THREAD

**Issue by ykartal** [mslosarz/nextrtc-example-videochat#25]
On example, I have tried rejoining same room without refreshing page after leave the room, join message is sent to server but video object is not added to container.

**Comment by mslosarz** [comment]
I'll take a look on it :)
EDIT:
The issue is on js client side. I'll fix it soon

**Comment by mslosarz** [comment]
Fixed :) Could you confirm?

**Comment by ykartal** [comment]
Yes, fixed, thanks ;)
