### ISSUE TITLE
if you use 'spring boot embeded server ', please make the following changes

### ISSUE THREAD

**Issue by yousky** [mslosarz/nextrtc-example-videochat#3]
**pom.xml**
Change spring-boot-starter-parent version
    1.2.1.RELEASE -> 1.2.5.RELEASE

**index.html**
Change url
    'ws://examples.nextrtc.org/videochat/signaling' -> 'ws://localhost:8080/signaling'

**SampleWebStaticApplication.java**
Add line

```
import org.springframework.context.annotation.Bean;
import org.springframework.web.socket.server.standard.ServerEndpointExporter;

//~~~~

@Bean
public MyEndpoint myEndpoint() {
    return new MyEndpoint();
}

@Bean
public ServerEndpointExporter serverEndpointExporter() {
    return new ServerEndpointExporter();
}
```

Thank you very much.
Your source code was very helpful.

**Comment by mslosarz** [comment]
I've changed parent pom version to this given by you.
I changed index.html url to localhost not to ws://localhost:8080/signaling but to ws://localhost:8080/videochat/signaling (I'll create branch only for spring embedded server and there your fix will be applied)
I didn't modify SampleWebStaticApplication

If you're still interested in this library you should take a look of latest version I've gathered all logic connected with spds exchange to one class (ConnectionContext), so it'll be easier in analyse :)
