### ISSUE TITLE
Building nextrtc-example-videochat

### ISSUE THREAD

**Issue by dimonik** [mslosarz/nextrtc-example-videochat#4]
When i do compilation inside Idea 15 i got:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nextRTCEndpoint' defined in URL

 [jar:file:/C:/Users/dimonik/.m2/repository/org/nextrtc/signalingserver/nextrtc-signaling-server/1.1.0-SNAPSHOT/nextrtc-signaling-server-1.1.0-SNAPSHOT.jar!/org/nextrtc/signalingserver/api/NextRTCEndpoint.class]:

Instantiation of bean failed;
nested exception is java.lang.NoClassDefFoundError: com/google/common/collect/Sets

What is com/google/common/collect/Sets?

**Comment by mslosarz** [comment]
This class comes from Guava, I'll check why this problem happened

**Comment by demoontz** [comment]
thanx for the answer!

in summary i succefully ran nextrtc-example-videochat in Wildfly8.2 and had video-call between two laptops in local network.
but
the dependency needs to be added:
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>18.0</version>
</dependency>
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.2.4</version>
</dependency>
<dependency>
    <groupId>joda-time</groupId>
    <artifactId>joda-time</artifactId>
    <version>2.9.1</version>
</dependency>
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.3.2</version>
</dependency>
and it not woking with remote client with nat. any suggestion about nat?
This two JS clients has some mention of "stun:stun.l.google.com:19302". But it seems that this STUN resolving doesn't work --- JS clients can communicate only inside LAN and can't do this over Internet - obvious, that incorrect IP+port is anounced inside SDP.
tommorow i`ll try to run with rest =)

**Comment by dimonik** [comment]
So questions are:

1) Why do we need to manually add dependencies to nextrtc-example-videochat?
I thought, that it should take all necessities from nextrtc-signaling-server library.

2) Why STUN resolving is not working in JS clients, any ideas?
Currently this JS clients only work in the same LAN.

**Comment by mslosarz** [comment]
I've check and JS client works in WAN, I suspect that you didn't provide
stun/turn server.

In JS client I'm using adapter.js from here:
https://github.com/webrtc/samples/blob/master/src/js/adapter.js

This adapter has basic to provide configuration for stun/turn server. You
have to provide configuration in js client as It was shown in my example:
https://github.com/mslosarz/nextrtc-example-videochat/blob/master/src/main/webapp/index.html
peerConfig : {
'iceServers' : [ {
url : "stun:stun.l.google.com:19302"
} ]
}

Ice servers configuration is similar to configuration in other solutions as
in:
http://easyrtc.com/docs/guides/easyrtc_server_ice.php

2015-12-19 12:35 GMT+01:00 dimonik notifications@github.com:

> So questions are:
> 
> 1) Why do we need to manually add dependencies to
> nextrtc-example-videochat?
> I thought, that it should take all necessities from
> nextrtc-signaling-server library.
> 
> 2) Why STUN resolving is not working in JS clients, any ideas?
> Currently this JS clients only work in the same LAN.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mslosarz/nextrtc-example-videochat/issues/4#issuecomment-165978113
> .

## 

Marcin Ślósarz

**Comment by mslosarz** [comment]
About dependencies.... It's hard to say. Maybe this dependencies should be
provided implicit in module configuration of wildfly. I don't know why this
problem occurs :(, but in Monday I'll check it

Thanks for your commitment in testing nextRTC :)

2015-12-19 12:59 GMT+01:00 Marcin Ślósarz m.slosarz@ahej.pl:

> I've check and JS client works in WAN, I suspect that you didn't provide
> stun/turn server.
> 
> In JS client I'm using adapter.js from here:
> https://github.com/webrtc/samples/blob/master/src/js/adapter.js
> 
> This adapter has basic to provide configuration for stun/turn server. You
> have to provide configuration in js client as It was shown in my example:
> 
> https://github.com/mslosarz/nextrtc-example-videochat/blob/master/src/main/webapp/index.html
> peerConfig : {
> 'iceServers' : [ {
> url : "stun:stun.l.google.com:19302"
> } ]
> }
> 
> Ice servers configuration is similar to configuration in other solutions
> as in:
> http://easyrtc.com/docs/guides/easyrtc_server_ice.php
> 
> 2015-12-19 12:35 GMT+01:00 dimonik notifications@github.com:
> 
> > So questions are:
> > 
> > 1) Why do we need to manually add dependencies to
> > nextrtc-example-videochat?
> > I thought, that it should take all necessities from
> > nextrtc-signaling-server library.
> > 
> > 2) Why STUN resolving is not working in JS clients, any ideas?
> > Currently this JS clients only work in the same LAN.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mslosarz/nextrtc-example-videochat/issues/4#issuecomment-165978113
> > .
> 
> ## 
> 
> Marcin Ślósarz

## 

Marcin Ślósarz

**Comment by dimonik** [comment]
Thank you for your work and for being so cooperative :+1:

**Comment by mslosarz** [comment]
I've run example at nextrtc.org
http://examples.nextrtc.org/videochat/
and now I suspect why you have problem with connecting in wide network.
I've got message in console like this:
{code}getUserMedia() no longer works on insecure origins. To use this
feature, you should consider switching your application to a secure origin,
such as HTTPS. See https://goo.gl/rStTGz for more details.{/code}

2015-12-19 14:06 GMT+01:00 dimonik notifications@github.com:

> Thank you for your work and for being so cooperative [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mslosarz/nextrtc-example-videochat/issues/4#issuecomment-165982888
> .

## 

Marcin Ślósarz

**Comment by mslosarz** [comment]
Example return back to normal. You can now check it at nextrtc.org
For problems with Wildfly please create new issue
