### ISSUE TITLE
Protocol between Client & Server

### ISSUE THREAD

**Issue by dimonik** [mslosarz/nextrtc-example-videochat#5]
JS clients are using JSON to communicate with your signaling server.

What is a valid format of the JSON Request (accepted by server)?

What i should say to server in order to get reply?

**Comment by dimonik** [comment]
I did Firebug on both browser-sides:
User_A which pressed 'Create' and
User_B which pressed 'Join'
and observed both logs in Firebug's Console->All screen.

Now everything seems to be clear.

**Comment by mslosarz** [comment]
I provide basic documentation. Signal exchange is described here
https://nextrtc.org/archives/62
